### ISSUE TITLE
Support URLS in file paths

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#131]
### Use Case

It would be helpful if a manifest could contain files located generally on the internet at a URL.

That's useful in a number of ways. 
- First, it would enable creation of manifests for publicly available datasets without moving their hosted location.
- It makes it possible to generate a pre-signed url for files in cloud storage, enabling temporary grant of permissions to access files without a GCP service account
- It makes it easy to create datasets from files managed by `django` with `django-storages`, which uses the pre-signed URL technique to grant access to files where `django` manages access control.

### Current state

Presently, only paths starting with `gs` or local file paths are supported.

**Comment by cortadocodes** [comment]
Update on the state of this:
- `Datafile` and `Dataset` now support signed Google Cloud Storage URLs
- Object metadata cannot yet be retrieved for datafiles instantiated from a signed URL
- Metadata is retrievable for datasets instantiated from a signed URL
- I don't think URLs that aren't Google Cloud Storage signed URLs currently work as datafiles, but I could easily verify this and it wouldn't take long to add this as a feature

**Comment by cortadocodes** [comment]
As of the latest release, general URLs are now supported as a read-only datafile source.
