### ISSUE TITLE
Ensure "path_from" and "absolute_path" information isn't lost from Pathables on serialisation

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#132]

**Comment by thclark** [comment]
Do we actually want to do this? Path-from requires that another object is present, which may not be true if the data file gets reused somewhere else. Absolute path is system specific, and I’d think we really don’t want that serialised...?

--
Sent from a mobile device; please forgive abrupt statements and 'auto-fill' mistakes!

Tom Clark
0776 453 0870

**Comment by cortadocodes** [comment]
I'm not sure, but the case I was thinking about is serialising a dataset and then deserialising it: the original dataset object and its datafiles will be different to the deserialised ones as they will no longer have any `path_from` information and possibly a different `absolute_path` (not in the case of cloud-located files). If `path` is relative, it seems to me that this could be a problem
