### ISSUE TITLE
Tags should support uppercase and slash characters

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#145]
### Use Case

We need to tag met mast files with strings including '/' and capital letters, in order to tag with a timezone... eg
```python
tags={"met-mast-id:mst1", "timezone:Asia/Kolkata"}
```
This raises the exception:
```
> octue.exceptions.InvalidTagException: Invalid tag 'timezone:Asia/Kolkata'. Tags must contain only characters 'a-z', '0-9', ':' and '-'. They must not start with '-' or ':'. 
```

### Current state

The only way of working around this to encode an IANA timezone would be to create a shared key:value map of timezones where the keys are compliant with tags. This is gross overkill!

**Comment by thclark** [comment]
NOTE: From [here](https://cloud.google.com/storage/docs/metadata#editable) we should be limiting to ASCII characters only to be compliant with gclouds XML api

**Comment by cortadocodes** [comment]
I've added this feature here: https://github.com/octue/octue-sdk-python/pull/152

All the allowed characters in a tag are ASCII, but not all ASCII characters are allowed in tags.
