### ISSUE TITLE
Key values in object metadata are stringified

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#146]
### What is the current behavior?

A number of object metadata items (id, hash_value, any null items) in gcloud storage are stringified rather than provided as raw values. For example the `id` field comprises the string `"45bf3bcb-92b0-45eb-9067-d8ecd173083d"` with quotation marks as opposed to the string literal `45bf3bcb-92b0-45eb-9067-d8ecd173083d`.

This prevents indexing/search in a data lake, and makes it very weird to create sdk-compatible file entries somewhere other than from the SDK.

![Screenshot 2021-05-02 at 10 35 27](https://user-images.githubusercontent.com/7223170/116808689-260c8000-ab32-11eb-8884-b5a7b98ef6ee.png)

### What is the expected behavior?

String items to appear without quotation marks, null values to appear as empty:

![Screenshot 2021-05-02 at 10 39 03](https://user-images.githubusercontent.com/7223170/116810548-4e00e100-ab3c-11eb-933e-723386c33328.png)

### Your environment

  - Library Version: `0.1.5`
  - Platform n/a

**Comment by cortadocodes** [comment]
The reason this happens is that the metadata is JSON encoded by the SDK; I'll see if we still need to do this!

**Comment by cortadocodes** [comment]
JSON encoding the metadata made getting and setting the metadata a bit smoother. Without it, we need to explicitly convert the values to the right types.
