### ISSUE TITLE
Improved ease of construction for object metadata

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#147]
### Use Case

I'm trying to use django storages to create datafiles which can be created / administered in django, but which can then be used by octue services.

To do that, I'm overloading the storage class' `_save` method to inject metadata from form fields in django, which means constructing the octue.Datafile object and getting metadata out of it. 

It'd be good to have a helper that would allow me to access the metadata dict directly, without doing a `to_cloud` operation.

Importantly, this would allow us to update the internals of the metadata management ourselves.

### Current state

Currently doing myself: 
```python
        meta = {
            "id": df.id,
            "timestamp": df.timestamp,
            "tags": df.tags.serialise(),
            "cluster": df.cluster,
            "sequence": df.sequence,
            "hash_value": df.hash_value,
        }
```

### Proposed solution

The `to_cloud` method uses a helper method to generate its own metadata, that can then be exposed for use in other storage mechanisms.
```python
    def metadata(self):
        return {
                "timestamp": self.timestamp,
                "id": self.id,
                "hash_value": self.hash_value,
                "cluster": self.cluster,
                "sequence": self.sequence,
                "tags": self.tags.serialise(to_string=False),
            }

    def to_cloud(self, project_name, bucket_name, path_in_bucket):
        """Upload a datafile to Google Cloud Storage.

        :param str project_name:
        :param str bucket_name:
        :param str path_in_bucket:
        :return str: gs:// path for datafile
        """
        GoogleCloudStorageClient(project_name=project_name).upload_file(
            local_path=self.get_local_path(),
            bucket_name=bucket_name,
            path_in_bucket=path_in_bucket,
            metadata=self.metadata(),
        )

        return storage.path.generate_gs_path(bucket_name, path_in_bucket)
```

**Comment by cortadocodes** [comment]
Ironically I actually created that method when I first did this work but removed it later as I thought I should just get the attributes! I can re-add it

**Comment by cortadocodes** [comment]
I've added the method here: https://github.com/octue/octue-sdk-python/pull/153
