### ISSUE TITLE
Use GCS custom_time as timestamp metadata storage

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#149]
### Use Case

GCS Allows a `custom_time` field to be associated with an object. If a non-null timestamp is provided to the Datafile, that is currently stored (as a posix timestamp) in the metadata, as a `timestamp` field.

However, using the GCS built in (fixed key) metadata to store this value, instead of our custom field, would allow us to more effectively filter timeseries files in the cloud store and elsewhere. It'd also allow us to encapsulate a relevant timezone where necessary.

Note that the storage client can accept timezoned `datetime.datetime` objects and they're serialized using [RFC3339](https://tools.ietf.org/html/rfc3339) as shown [here](https://github.com/googleapis/python-storage/blob/9777904b7237fd228d160fa65e7a419aefe414f6/google/cloud/storage/blob.py#L3956) which is a useful trick for us to use in future then we need to serialize datetimes.

![Screenshot 2021-05-02 at 13 00 13](https://user-images.githubusercontent.com/7223170/116812357-5d852780-ab46-11eb-8442-fd45d0461da4.png)

**Comment by thclark** [comment]
NOPE!

We have to undo this.

I've just discovered that GCS' custom_time metadata is dumb as fuck.

![Screenshot 2021-05-07 at 13 06 26](https://user-images.githubusercontent.com/7223170/117447508-871ec400-af35-11eb-94e2-29a7f658d0f0.png)

So you can't change metadata that's incorrect.

we'll need to store in our own timestamp field after all, sorry @cortadocodes  :(

**Comment by cortadocodes** [comment]
Reverted here: https://github.com/octue/octue-sdk-python/pull/160
