### ISSUE TITLE
Bullet points aren't rendering on hosted docs

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#170]
Bullet points show up on the locally built docs but not on the hosted ones - they show up as just being lines of text with no indentation instead e.g. https://octue-python-sdk.readthedocs.io/en/latest/filter_containers.html

**Comment by thclark** [comment]
With frontend styling issues, a screenshot is worth a thousand words is what we're discovering over on windquest. Can you add before/after screenshots?

Do you build the docs with `pre-commit`? I'm wondering if the dependencies for that are identical to the ones in the docs folder that readthedocs uses...

**Comment by cortadocodes** [comment]
![Screenshot 2021-05-26 at 12 09 38](https://user-images.githubusercontent.com/33758634/119650029-4242ca80-be1b-11eb-9e6a-08032fcc37d2.png)

On this page in the screenshot, all of the preformatted text should also be bullet pointed

**Comment by cortadocodes** [comment]
![Screenshot 2021-05-26 at 12 11 09](https://user-images.githubusercontent.com/33758634/119650215-77e7b380-be1b-11eb-9c81-e27d317c8919.png)

When built and served locally, they're rendered correctly

**Comment by cortadocodes** [comment]
Note that these two screenshots are on different branches, but I'm fairly sure the problem remains

**Comment by thclark** [comment]
wow, that's not correct at all. That latter one is built with a totally different theme. How are you building that?

**Comment by cortadocodes** [comment]
I was wondering about that. It's just what `pre-commit` is building
