### ISSUE TITLE
Cannot instantiate a datafile from a raw cloud object

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#200]
### What is the current behavior?

If I try to instantiate a datafile from an object in the cloud which was not initiallu uploaded with an `octue__id` metadata entry,  it is impossible, because I get the following warning:
```
WARNING  octue.resources.datafile:datafile.py:371 The value None of the Datafile attribute 'id' from the cloud conflicts with the value given locally at instantiation '48b63b26-074b-4b7f-9428-c1d2e1ce1481'. This may not be a problem, but note that cloud datafile metadata cannot be changed at instantiation. The cloud value has been used.
```

This `None` value then prevents propagation of the metadata to the cloud.

### What is the expected behavior?

Be able to instantiate a datafile from a raw object previously untreated with octue

**Comment by cortadocodes** [comment]
Could I check if you explicitly gave this datafile and `id` at instantiation? Actually could you share the code snippet used to make the datafile?
