### ISSUE TITLE
Need ability to extract cloud path parts, and test for cloudiness of file

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#204]
### Use Case

I'm trying to use django storages to create records of Datafiles, and sync their metadata into a database. To do that, I need to access `path_in_bucket`.

### Current state

First, I instantiate `Datafile`s from their cloud paths, so I instantiate them without downloading the entire bucket contents:

```python
        # Get a dict of Datafile objects keyed on their id, one for each object in the store
        datafiles_in_store = dict()
        for blob in storage.client.list_blobs(bucket_or_name=storage.bucket_name):
            gs_path = f"gs://{storage.bucket_name}/{blob.name}"
            datafile = Datafile(gs_path, project_name=storage.project_id, hypothetical=True)
            datafiles_in_store[datafile.id] = datafile
```

I then cache these datafiles and work with them **elsewhere** to synchronise a database table where each row comprises the path_in_bucket and metadata of that file.

In my synchronisation, I need to create rows corresponding to files that are not already in the DB, so I do:
```python

instance = MyModel(id=datafile.id)
instance.update_instance_from_tags(datafile.tags)   # A custom method to turn octue tags into db fields
instance.update_instance_from_labels(datafile.labels)  # A custom method to turn octue labels into db fields

# Argh what a pain that datafile knows where it is but I still have to do this surgery
if datafile.path.startswith("gs://"):
    path_in_bucket = datafile.path.replace("gs://", "").split("/", 1)[1]
else:
    path_in_bucket = datafile.path.lstrip("/")
    
# Set the file field .name attribute directly to path within bucket (https://stackoverflow.com/a/10906037/3556110)
instance.file_field.name = path_in_bucket
```

### Suggested improvement

I think that once I've defined a `Datafile` as being in the cloud:

- It should be straightforward to access parts of the cloud path properties, like `my_datafile.path_in_bucket` or `(protocol, project_name, bucket_name, path_in_bucket) = my_datafile.cloud_path_parts()`
- If I want to use the `update_metadata()` method, I shouldn't have to tell it *again* where the file is...
    ```python
    df = Datafile(gs_path)
    df.update_metadata(..., cloud_path=gs_path) # Why doesn't it know this already?
    ```
- It should be straightforward to test whether the file exists locally, or in cloud, or both:
    ```python
    df = Datafile(some_path_which_may_be_local_or_gs)
    if df.local_path is not None:
        print('file exists locally')
    if df.cloud_path is not None:
        print('file exists in cloud')
    ```
- Instantiating a datafile with `path=gs_path` should throw an exception if `project_name` not also defined (*nb it might do this already*):
    ```python
    df = Datafile('gs://my-bucket/my-file.txt')
    > ValueError('You cannot instantiate a Datafile from a cloud path without also specifying a project_name')

### Additional documentation

I think this is probably also worth doing with an additional / expanded section in the docs on "working with datafiles", expanding on the four use cases that are already there and explaining some of these patterns and concepts.

**Comment by cortadocodes** [comment]
> It should be straightforward to access parts of the cloud path properties, like my_datafile.path_in_bucket or (protocol, project_name, bucket_name, path_in_bucket) = my_datafile.cloud_path_parts()
I agree, I can surface this as it is available under the hood.

> If I want to use the update_metadata() method, I shouldn't have to tell it again where the file is
You don't have to, you can just call it without the parameters (perhaps I should make that clearer in the docs?). Also the method is now called `update_cloud_metadata`

>It should be straightforward to test whether the file exists locally, or in cloud, or both
There's a property called `datafile.is_in_cloud` - is this enough or do we need a `datafile.is_local` or similar too?

> Instantiating a datafile with path=gs_path should throw an exception if project_name not also defined (nb it might do this already)
An error will be thrown but it might not be as helpful as the one you wrote - I can implement that one.

**Comment by thclark** [comment]
> > It should be straightforward to access parts of the cloud path properties, like my_datafile.path_in_bucket or (protocol, project_name, bucket_name, path_in_bucket) = my_datafile.cloud_path_parts()
> 
> I agree, I can surface this as it is available under the hood.
Great, yes please :)

> > If I want to use the update_metadata() method, I shouldn't have to tell it again where the file is
> 
> You don't have to, you can just call it without the parameters (perhaps I should make that clearer in the docs?). Also the method is now called `update_cloud_metadata`

So what's the point of having the parameters? I kind of feel like if that information is missing it should be somehow set explicitly (via instantiation with the cloud path, or by a set_cloud_path() method) rather than in the metadata update method.

> > It should be straightforward to test whether the file exists locally, or in cloud, or both
> 
> There's a property called `datafile.is_in_cloud` - is this enough or do we need a `datafile.is_local` or similar too?
Yes we do, because it's possible for both things to be true. How do we get the cloud and local paths?

> > Instantiating a datafile with path=gs_path should throw an exception if project_name not also defined (nb it might do this already)
> 
> An error will be thrown but it might not be as helpful as the one you wrote - I can implement that one.
Yeah, make it clear what's going wrong. To be fair I didn't actually check this so it might be fine.

**Comment by cortadocodes** [comment]
> So what's the point of having the parameters? I kind of feel like if that information is missing it should be somehow set explicitly (via instantiation with the cloud path, or by a set_cloud_path() method) rather than in the metadata update method.

I originally thought you might want to change where you upload the datafile to after downloading, so I made it so using any cloud method will cause the datafile to remember that cloud location for the next use of any cloud method but also you could override that by putting in a different location. Do you think we should disallow that and just make the user make a new datafile if they want a new location? It would make the API nicer and probably make things simpler

**Comment by thclark** [comment]
> > So what's the point of having the parameters? I kind of feel like if that information is missing it should be somehow set explicitly (via instantiation with the cloud path, or by a set_cloud_path() method) rather than in the metadata update method.
> 
> I originally thought you might want to change where you upload the datafile to after downloading, so I made it so using any cloud method will cause the datafile to remember that cloud location for the next use of any cloud method but also you could override that by putting in a different location. Do you think we should disallow that and just make the user make a new datafile if they want a new location? It would make the API nicer and probably make things simpler
> 
> > Yes we do, because it's possible for both, neither or one of the things to be true. How do we get the cloud and local paths?
> 
> Cool I'll add that. If it's in the cloud, `datafile.path` is the cloud path and `datafile.get_local_path()` gives you the path to the temporary file it's downloaded to locally. So far, there isn't a solution to having a local file, uploading it to the cloud, and then continuing to work on it locally. It will just be downloaded again to a temporary file and edited there which isn't idea. I can easily fix this so it uses the original local file instead

Yeah, I think that's more intuitive. Also, can you add `cloud_path` and `local_path` as properties so it's explicit where stuff is locally and in the cloud (returning None if not present in cloud/local) please? Because it's possible for `path` to be specified as either local or remote, it makes it very confusing to then say `datafile.path` is the cloud path.

**Comment by cortadocodes** [comment]
Yep sure. What do you want `path` to be equal to when there's both a `cloud_path` and a `local_path`? Maybe path should be the name of the parameter but then only `cloud_path` and `local_path` be attributes on the datafile?

**Comment by thclark** [comment]
Well we're using `path` so I'd keep it as whatever it currently is. Perhaps we explicitly deprecate it after a while.

**Comment by cortadocodes** [comment]
As part of this, I think we should add the ability for this sequence of events:
1. Make a local file/datafile
2. Upload it to the cloud
3. When editing the (now cloud-linked) datafile, the local file used to stage the edits before updating the cloud object is the original local file, not a temporary file

This means local and cloud datafile changes are in sync and also removes the need for an extra download from the cloud.
