### ISSUE TITLE
Allow `one` method to work on a `files` Filterset that's not been filtered or ordered

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#245]
### Use Case

I want to manage cases where a dataset has a single file in it, using a shorthand.

### Current state

If I do:
```
my_dataset.files[0]
```

I get `FilterSet is not subscriptable` error., because `.files` derives from `set` which is inherently unordered. I totally agree with this architecture (we've had this discussion) because we shouldn't be relying on a dataset to be ordered intrinsically (ie without actually specifying what it's ordered by).

But, it's unintuitive not to reach straight in for `.files[0]` to get the "first" one.

So what I do is:
```
assert(len(my_dataset.files) == 0)
my_one_and_only_file = next(iter(my_dataset.files))
```

### Proposed solution

Related to #239 in the sense that this should assert presence of a single file.

Suggest that we have a `files.one()` method in the `FilterSet` mixin that uses the above snippet to assert there's only one and return it from the set.

**Comment by cortadocodes** [comment]
I'd forgotten there is actually a `FilterContainer.one` method (`FilterContainer` is the base class for `FilterSet` etc.). I'll check now that it does exactly what we want here.

**Comment by thclark** [comment]
We've reached the point where our API is so useful that we forget how useful it is. Basically we're django 😎

**Comment by thclark** [comment]
Meh, it doesn't.
```
>>> len(elevation_map_dataset.files)
1
>>> a = elevation_map_dataset.files.one()
Traceback (most recent call last):
  File "/home/vscode/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 419, in evaluate_expression
    compiled = compile(_expression_to_evaluate(expression), '<string>', 'eval')
  File "<string>", line 1
    a = elevation_map_dataset.files.one()
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vscode/.local/lib/python3.9/site-packages/octue/resources/filter_containers.py", line 92, in one
    if len(results) > 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by thclark** [comment]
although maybe it *should* work as expected and we've found a bug?

**Comment by cortadocodes** [comment]
No it's been written so that a filter has to be provided when calling `one` - I'm just changing that now
