### ISSUE TITLE
Make strands explicit attributes on Analysis class

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#261]
# Feature request

## Current state
Currently, strands (e.g. `input_values`, `input_manifest`, `children`) don't appear as explicit attributes on `Analysis` instances. Instead, they're added dynamically if they are defined on the corresponding twine. This leads to code introspection falsely reporting that these attributes definitely don't exist on `Analysis` instances (see image below) and an interface that isn't constant.

![Screenshot 2021-10-13 at 15 46 40](https://user-images.githubusercontent.com/33758634/137157106-c622e62a-1183-46cd-a500-caca991334a4.png)

## Future state
I think it would be clearer if all the possible strands existed as explicitly-defined attributes on `Analysis` with their value just set to `None` if they don't exist in the corresponding twine.

**Comment by thclark** [comment]
I had this before and a certain someone removed it ;)

But sure, I'm happy with that. Just need to take care on the serialisation because you'll not want to serialise the `None` values
