### ISSUE TITLE
Clarify warning about missing `GOOGLE_APPLICATION_CREDENTIALS` when `credentials=None` is given

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#270]
This warning is misleading - it suggests a problem where there isn't one. Replace it with an `info` log message.

**Comment by thclark** [comment]
It'll pick up a credentials file automagically so you might have to delete your credentials file as well as unsetting the environment variable

**Comment by cortadocodes** [comment]
Please could you link to an example of the error @thclark?
