### ISSUE TITLE
Clean up cli testing to avoid race conditions

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#32]
Tests that run the CLI create `output` directories that currently need to be deleted manually.

That's mildly annoying but indicative of a deeper concern that race conditions may exist between tests if executed in parallel and using the default directory

Use or adapt the `callCli` method of BaseTestCase throughout to ensure that cli calls are done in their own `NamedTemporaryDirectory` context, ensuring that artifacts are automatically cleaned up and that tests are deterministic

**Comment by cortadocodes** [comment]
It doesn't look like `callCli` is used - could this be why this is happening?

**Comment by cortadocodes** [comment]
It seems to be the last three tests in `test_cli.py` that are causing this leakage rather than the template apps as I'd thought.
