### ISSUE TITLE
Log analysis to socket

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#35]
When setting up the analysis logging, optionally create an additional handler to send log entries to a websocket, whose a URI could be passed as a CLI option then into the runner.

This will enable the logs from the analyses to be streamed back to the end user.

@cortadocodes how do you feel about taking this one on?

### Testing

I'm not sure how to create a websocket for testing purposes but it must be doable.

**Comment by cortadocodes** [comment]
Sounds good!

**Comment by thclark** [comment]
I'm working over in [django-twined](https://github.com/octue/django-twined) on the task broker and am calling the parameter `logger_uri`

**Comment by cortadocodes** [comment]
> I'm not sure how to create a websocket for testing purposes but it must be doable.

@thclark would this be to test the ability to stream log output to a URI?

**Comment by thclark** [comment]
> > I'm not sure how to create a websocket for testing purposes but it must be doable.
> 
> @thclark would this be to test the ability to stream log output to a URI?

Yes.

**Comment by cortadocodes** [comment]
Did you want this to accept `ws` and `wss` protocols as well as `http` and `https`?

**Comment by thclark** [comment]
I've perhaps skimmed too quickly. How can you log to a websocket over `https`? Surely this should *only be* `ws` and `wss`?

**Comment by cortadocodes** [comment]
I think websockets are compatible with `https` although the main reason is that I assumed websocket meant an `http` port. I'll look into and amend this now.
