### ISSUE TITLE
Remove `store_datasets` parameter from `Manifest.to_cloud`

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#358]
I'm not sure it makes sense to upload all datasets in a manifest to the same directory as the manifest file because:
- A manifest can contain any number of datasets from anywhere
- It tightly couples the manifest to the datasets, when the datasets are supposed to just reside where they already are
- A manifest is supposed (I think) to be a lightweight listing of all datasets required for an analysis, not an object that lugs all its datasets with it

This also raises the question of whether we even need a `Manifest.to_cloud` or `Manifest.from_cloud` command.

**Comment by cortadocodes** [comment]
Great! Just to check - you're saying remove `store_datasets` parameter but keep `Manifest.to_cloud` method?

**Comment by thclark** [comment]
Remove the store _datasets V parameter for now. I think to_cloud and from_cloud are still useful shortcuts, but might be able to be simplified right down to simply invoking to/from_cloud on the set of datasets
