### ISSUE TITLE
Should datasets be strictly one of {cloud-based, local} with no crossover?

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#364]

**Comment by cortadocodes** [comment]
## Initial questions
There are two questions I've been confronted with:
1. What does it mean for a dataset to have a path when its files reside either:
  - Some locally, some on the cloud
  - All in the cloud, but in different buckets
2. Assuming that the dataset contains files either only locally or from one cloud bucket, can an entire dataset exist simultaneously in the cloud and locally with changes to the dataset locally being pushed to the cloud (like a datafile can)? I call this cloud/local duality.

## 1. Datasets and paths
It seems reasonable that a dataset could contain cloud file and local files, but this makes the dataset's path confusing and possibly meaningless. It also means that the dataset can't be transferred to anywhere other than the same local machine. The resolutions to this situation seem to be either:
- Remove the concept of a path from datasets and allow datasets to contain any mixture of cloud and local files, leaving the user to guarantee that each dataset's files are accessible wherever they use the dataset instance
- Or, (strictly?) limit a single dataset to comprise either files from just one cloud bucket, or just files from a local system. I'm in favour of this option currently. This option gives us a tighter and easier-to-implement definition of what a dataset is while still leaving us manifests that can point to any number of cloud datasets and local datasets. It also means the path attribute of a dataset is always meaningful. Currently the dataset seems to be so unconstrained as to essentially be a manifest.

## 2. Dataset metadata cloud/local duality
Datafiles can exist simultaneously in the cloud and locally with changes made locally being pushed to the cloud. Dataset instances (i.e. their metadata) currently can't, although all of their datafiles still can. I think it makes sense to, at least for now, just allow local/cloud duality on a dataset's files, but only persist information about a dataset either in the cloud or locally, but not both. Alternatively, as I'm writing this, I can envisage duality for the dataset's metadata via a dedicated datafile just for this purpose.

**Comment by thclark** [comment]
Decision made: I think we can afford to remove the functionality of pathabilty from Datasets, because it's caused so many problems over the last year and presently isn't adding much functionality.
That way, a lot of the above falls out more easily.

> Or, (strictly?) limit a single dataset to comprise either files from just one cloud bucket, or just files from a local system. I'm in favour of this option currently. This option gives us a tighter and easier-to-implement definition of what a dataset is while still leaving us manifests that can point to any number of cloud datasets and local datasets. It also means the path attribute of a dataset is always meaningful. Currently the dataset seems to be so unconstrained as to essentially be a manifest.

**DECISION:** We will say that a dataset is in a single bucket. It may not comprise **all** the files in that bucket though. Inherently then, a dataset *does* have a cloud path (i.e. the bucket address) but this doesn't necessarily need to be pathable locally.

**Comment by cortadocodes** [comment]
As part of this decision, when adding a datafile to a dataset, we need to provide the path within the dataset to add it to:
- The default will be to put it at the root of the bucket
- If the datafile exists locally in the dataset's local location, its default location within the cloud dataset should be deduced automatically

```
def add(datafile, path_in_dataset):
    ...
```

When adding a file not in the cloud dataset, we also need to push it to the cloud.

**Comment by cortadocodes** [comment]
We're arriving at a clearer distinction of what local and cloud datasets are:
- Local dataset:
  - Based around a local directory
  - Metadata is stored locally
  - Not guaranteed to be available outside the local machine

- Cloud dataset:
  - Based around a cloud directory
  - Metadata is stored in cloud
  - Guaranteed to be available outside the local machine (with the correct permissions)

The files in both types of dataset can have local/cloud duality but the following restrictions apply:
- A local dataset should not have files that are purely cloud-based
- A cloud dataset should not have files that are purely local
