### ISSUE TITLE
Test race condition

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#377]
### What is the current behavior?

Sometimes, sdk tests fail with the following error:
```
======================================================================
ERROR: test_stdout_is_logged (tests.utils.test_processes.TestRunSubprocessAndLogStdoutAndStderr)
Test that any output to stdout from a subprocess is logged.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/octue-sdk-python/octue-sdk-python/tests/utils/test_processes.py", line 35, in test_stdout_is_logged
    self.assertEqual(mock_logger.info.call_args_list[1][0][0], "goodbye")
IndexError: list index out of range
```

The problem appears spontaneously ([these fail](https://github.com/octue/octue-sdk-python/actions/runs/1982079818) while [these pass](https://github.com/octue/octue-sdk-python/actions/runs/1982087311) on the same code) so there's likely to be a race condition between some of the tests.

### What is the expected behavior?

Consistent test passing.

### Your environment

Github Actions

**Comment by cortadocodes** [comment]
I haven't seen this fail in a while so I'll close it and we can re-open if necessary.
