### ISSUE TITLE
Remove travis builds

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#39]
Remove travis file from repo for #36 now that github actions are used instead.

**Comment by cortadocodes** [comment]
I'm assuming I should remove the Travis 'build passing' sticker too?

**Comment by cortadocodes** [comment]
Cool done! I think you'll still have to disable the Travis check thats set up on GitHub yourself as I don't have permission

**Comment by thclark** [comment]
Great. I think it'll just die with no travis file, but will double check.
