### ISSUE TITLE
Github Action Version Check

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#40]
If we're on a branch, `release/x.y.z`, then the version from `setup.py` should be matching `x.y.z`.

Create a check in github actions that fails if it doesn't match, apply it to this repo and all the others where github actions are used (e.g. twined, django-twined etc etc)

@cortadocodes this is busy work for filling in gap time, not high priority right now.

**Comment by cortadocodes** [comment]
I'll set this to trigger when a pull request is made for the release branch.

**Comment by cortadocodes** [comment]
I've written something and added it to #42 for review. After it's approved, I think it would be a good idea to move it to a separate repository of GitHub actions so we can use it in all repositories without repeating code.

**Comment by cortadocodes** [comment]
This is now merged into `twined` and `octue-sdk-python`'s next releases. I'll add it to other repos later.
