### ISSUE TITLE
Update google-cloud-storage version

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#420]
### Use Case

In [`django-gcp`](https://github.com/octue/django-gcp) we have utilities to interact with google cloud store via django. The objective of this library is that we should be able to use [`django-twined`](https://gihub.com/octue/django-twined) to tie the Octue SDK with django's storage and event handling abilities.

In this way, we get django's out of the box admin views for our the cloud stores - we can query for datasets, ask questions, listen to responses and manage services all from one admin panel. We can also orchestrate wider use of services through a completely generic API.

However, we currently can't install octue 0.18.0 alongside django-gcp 0.3.0 because the version of `google-cloud-storage` is incompatible:

```
$ poetry update
Skipping virtualenv creation, as specified in config file.
Updating dependencies
Resolving dependencies... (0.9s)

  SolverProblemError

  Because no versions of django-gcp match >0.3.0,<0.4.0
   and django-gcp (0.3.0) depends on google-cloud-storage (>=2.1.0,<3.0.0), django-gcp (>=0.3.0,<0.4.0) requires google-cloud-storage (>=2.1.0,<3.0.0).
  And because octue (0.18.0) depends on google-cloud-storage (>=1.35.1,<2.0.0)
   and no versions of octue match >0.18.0,<0.19.0, django-gcp (>=0.3.0,<0.4.0) is incompatible with octue (>=0.18.0,<0.19.0).
  So, because django-twined depends on both octue (^0.18.0) and django-gcp (^0.3.0), version solving failed.
```

### Proposed solution

Allow octue to use the newer version of the `google-cloud-storage` library

### Current state

`google-cloud-storage` version is set to `google-cloud-storage = "^1.35.1"`.

**Comment by thclark** [comment]
The [changelog](https://googleapis.dev/python/storage/latest/changelog.html) suggests that the only breaking change is to remove python 2 support, meaning that we can probably upgrade transparently.

**Comment by cortadocodes** [comment]
@thclark is this now fixed?
