### ISSUE TITLE
Make test resources idempotent and separate from production resources

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#421]
### What is the current behavior?

- During testing, buckets seem to be created (`bucket-of-sand`, `bucket-of-chocolate` etc) but not destroyed, leading to race conditions in tests (tests fail when the buckets are already instantiated - I don't know how tests pass routinely, are you deleting test buckets in a different script @cortadocodes ?).

- There's no consistent naming pattern in the buckets, so in the gcloud console, it's difficult to tell which are which (they're alongside all the production buckets)

- The base test bucket is called `octue-test-bucket` which isn't specific, because we have lots of test buckets

- Tests are done in our production project, which is quite risky (for example listing and deleting all buckets could bring down operations).

### Suggested improvements:

- [x] Use a specific prefix for all buckets used  in testing (including the base test bucket), e.g `sdk-python-test-bucket`, `sdk-python-test-bucket-<whatever>`
- [x] If the base test bucket does not exist, create it in the tests, enabling easy change of project or periodic clearup of resources
- [ ] When creating buckets (or any resources) during a test, create them with unique names to avoid collision between multiple test runners. You could use a coolname generator which will help with diagnosis (e.g. `sdk-test-bucket-of-crazy-bananas`)
- [x] During tests, store the names of the resources you create, and in teardown, delete them.
- [x] Create a new project, say `octue-sdk` and shift the testing over to it.
- [ ] Make a periodic task in the project (see cloud scheduler) to run weekly and delete all buckets prefixed with `sdk-python-test-bucket` - that way any tests which crash badly (and therefore don't get torn down correctly) won't leave resources hanging around
- [ ] Update the credentials for the new project.
- [x] Either make the `TEST_PROJECT_ID` in `tests/__init__.py` correct and used, or remove it (presently it's being ignored and the credentials are used to infer project ID).

**Comment by cortadocodes** [comment]
These are great points. I plan to implement all of the above!

**Comment by cortadocodes** [comment]
The SDK is using a cloud storage emulator so most, if not all, of the files in this test bucket were put there before I added the emulator or on the rare occurrence when it wasn't working or I needed to use a real bucket for some reason. I've removed all the files from it and will check if anything gets added during a full test run.

**Comment by cortadocodes** [comment]
Update: I've deleted all the tests buckets from the SDK and confirmed they're not recreated by running the tests.

Separate point - the `TEST_PROJECT_NAME` is used, but only for Pub/Sub-related tests:

> Either make the TEST_PROJECT_ID in tests/__init__.py correct and used, or remove it (presently it's being ignored and the credentials are used to infer project ID).
