### ISSUE TITLE
Additional helper methods on Taggables

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#43]
**I'm submitting a ...**
  - [x] feature request
  
### Use Case

> Please descrie your use case

I'm trying to extract tags (and subtags) from taggable groups.

e.g if I have a datafile entry with:
```
{
   tags: `a-tag another:23`
}
```
That gives me a TagGroup object.

I want to be able to get `23` easily so that I can use it in searching for other files. with the same tag.

### Current state

> Please describe what you're doing presently to work around this or achieve what you're doing.

workaround by doing str(tags) then manually parsing the string with a loop. very annoying.

**Comment by thclark** [comment]
@time-trader you might want to follow this

**Comment by cortadocodes** [comment]
@thclark do you want the `startswith` etc methods to be able to work on subtags too? Or just be able to get subtags from a `TagGroup`?

**Comment by thclark** [comment]
And/Or some similar useful APIs, yes, that'd be elegant. `contains` might be a good one too.

Perhaps this is a good opportunity to implement a chainable filter on TagGroup which could work like a list except with extra methods to filter further - so you could go, for example:
```
<thing>.getTags.startswith('meta').contains('sys2').subTags()[-1]
```
 which, if applied to a `Taggable` with `tags="tag1 tag2 meta:sys1:1234 meta:sys2:3456"` would result in `3456`.

**Comment by thclark** [comment]
The other side of the problem is needing to be able to test against tags, for ~~searching~~ matching files in a manifest.

This is where we really should be using a search index and lucene syntax, which we could do trivially if this were online-only. But there aren't any native python implementations (everything requires a JVM, and I foresee trouble ahead with that...), and being able to do it locally would be helpful.

But, we could implement a `has` method on the taggable class that returns T/F given the filters above. 

That'd allow us to implement a `match_files()` method on a a Dataset which would implement a crude O(MN) search (M = no. tags, N = no. files) for files meeting those criteria.

**Comment by cortadocodes** [comment]
I've implemented chained filtering 💯 Isn't the proposed `has` method the same as `__contains__`?

**Comment by thclark** [comment]
> @thclark I've implemented chained filtering 💯 Isn't the proposed `has` method the same as `__contains__`?

It certainly can be, but I don't know whether we want to use `__contains__` for that. Probably don't want to overload such an important method in a mixin.

For example, a `Dataset` is a `Taggable` but you'd want to reserve `__contains__` for much more obvious uses like `if <DataFile> in Dataset`.

**Comment by thclark** [comment]
Maybe we use something more descriptive though, like `has_tag` or `has_tags`

**Comment by cortadocodes** [comment]
I've swapped `__contains__` for `has_tag` but I've just realised that it doesn't matter if we have loads of magic methods for `TagGroup` as it's not a mixin - its instances are used as an attribute of a mixin.
