### ISSUE TITLE
Add hashes of input data

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#44]
**I'm submitting a ...**
  - [ ] support request
  - [ ] bug report
  - [x] feature request
  
Please fill out the relevant sections below.

---

### Use Case

> Please [describe your motivation and use case].

I need to be able to check that a particular set of inputs was used to create an output.

Hashes of input_values, configuration_values, input_manifest, configuration_manifest, made available on the analysis object, would allow me to tag output data with the input hashes for auditability.

- [x] Add the hashes and attach to analysis object
- [ ] Add a section in the documentation (and/or an app demo template) describing usage.

**Comment by thclark** [comment]
@time-trader you might want to follow this

**Comment by cortadocodes** [comment]
@thclark I'm assuming this will be a hash of the files themselves in the manifests rather than hashes of the filenames

**Comment by cortadocodes** [comment]
`BLAKE2` seems like a pretty good option - faster than `SHA` (see https://www.blake2.net)

**Comment by cortadocodes** [comment]
Actually I'm wondering whether the computational overhead of hashing all the files is worth it if the names of the files are adequately organised. What do you think?
