### ISSUE TITLE
Allow easy retrieval of fixture data

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#451]
### Use Case

We have a child service A that accepts data in `input_values` and an `input_manifest`. It processes the files in the manifest to compute the `output_values`.

This is asked a question by a parent service B, which in turn is given inputs by a grandparent service C.

Sometimes, a problem occurs in A - usually this is due to poorly conditioned contents of the files in the input manifest. In some cases we can detect this and raise the correct error message (suitable to go back and prepare different input files) whilst in other cases further investigation is required (to develop better error handling or account for the edge case).

If further investigation is required, we need to manually recreate the inputs to that service - i.e. **create a test fixture**.

### Current state

Creating this test fixture is very problematic. It's trivial to reconstruct inputs of the parent service B, because we log them ourselves in the grandparent C when we ask the question... but the parent service processes those to determine inputs to the child A.

In order to obtain our test fixture for Child A, we presently:
 - run Parent B locally (which means also running Grandparent C locally, to access it)
 - modify Parent B's code to intercept the question being asked to Child A
 - save the intercepted question
 - use the saved question to construct a test fixture

### Proposed solution

- [x] Add an aspect to the app configuration which gives a service a `gs_path` to its own 'fixtures' bucket (to which it has **write-only** permission).
  - [ ] Write-only is important because it prevents creation of an attack surface whereby a malicious actor penetrating the service could use that to pull fixtures data from other questions.
- [x] Add a boolean parameter, say `allow-persist-diagnostics-data` which is default `True`, to the question, which gives permission to Child A to "gather crash data for diagnosis".
  - [x] Permission to access the input data is already given to the Child A implicitly, but it might be done with expiring tokens in the gs paths. This is essentially permission to keep data for longer in order to do diagnosis.
- [x] Add a handler to the runner which, on raise of an exception out of the question (and given both a fixtures path and permission from the asking question):
  - [x] creates a question-specific subfolder in the fixtures bucket
  - [x] writes the log to it (if possible, maybe the log's not fully buffered locally?)
  - [x] copies the full datasets (whilst the URLs for the files are still valid) to the subfolder
  - [x] writes the input_values, input_manifest, configuration and any other requisite metadata to it...
    - [x]  updating paths and stripping tokens within the input manifest so the fixture can be recreated out-of-the-box (i.e. points to the copy of the fixture data not the original)
- [x] Send a message back to the parent with the gs path of the fixture
- [x] Add a fixture downloader where, from a developer machine with **read** credentials to the fixtures bucket, you can do something like `octue get-fixture <gs_path> --save-to <local_path>`

**Comment by thclark** [comment]
@nvn-nil I'd appreciate you casting an eye over this - do you think this covers everything in terms of creating test fixtures much quicker that we were talking about this morning?

**Comment by nvn-nil** [comment]
Yes, this is much better than what I had in mind.

**Comment by cortadocodes** [comment]
> Add an aspect to the app configuration which gives a service a gs_path to its own 'fixtures' bucket (to which it has write-only permission)

I think this can only be controlled externally to the SDK - is that correct @thclark?
