### ISSUE TITLE
Improve validation of input parameters in Dataset instantiation

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#452]
When instantiating a dataset, all the arguments are parameters, but can be given in positional order;
```py
Dataset(my_list_of_datafiles)  # works
```

The following bug report arose because I converted `Dataset.from_local_directory(my_path)` to `Dataset(my_path)` rather than `Dataset(path=my_path)` - which actually worked, and I ended up with a long list of files because the string-like resulting from `os.path.join` is iterable, so Dataset's `__init__` method saw it as a list of files.

I feel like this could have been caught and perhaps we could do better input validation and helping to spot problems like this?

<details>
<summary>
The following bug report arose because I instantiated incorrectly
</summary>

### What is the current behavior?

Previously (0.23.x) I was using `Dataset.from_local_directory(local_path)` to generate a `Dataset` from a local path, which is now removed in 0.24.0 and replaced with a uniform instantiation `Dataset(local_path)`.

If not given a name parameter, the dataset name would be set from the lowest directory in the `local_path`. Now, the default name given to a dataset is determined by the service (see the debug toolbar on the left):

Previous:
<img width="1260" alt="Screenshot 2022-05-13 at 10 19 01" src="https://user-images.githubusercontent.com/7223170/168253051-d342be7a-f5de-425f-9d3b-af507f0dbe40.png">

With 0.24.0:
<img width="1292" alt="Screenshot 2022-05-13 at 10 14 56" src="https://user-images.githubusercontent.com/7223170/168253795-fc731101-5d6e-4f54-801a-d9e14feb2a36.png">

### What is the expected behavior?

Instantiation of a local dataset from a local path should have a default name corresponding to the last part of that path.

</details>

**Comment by cortadocodes** [comment]
This is a good point about validation. I've run the test you've screenshotted, however, and I don't get the representation of the dataset that you get. I get `<Dataset('wind_speed_map')>`?
