### ISSUE TITLE
Run CI tests on `python3.9`

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#479]

**Comment by thclark** [comment]
@cortadocodes why do we need to consider this? Surely this should be a labelled devops issue and we should be taking it for granted that we'll do this? (Also, why aren't they run on 3.9 already? We've been using 3.9 for most of our service for more than a year, so can you elaborate on what the difficulty is with testing please?)

**Comment by cortadocodes** [comment]
There's no difficulty, we've just been running them on python3.8 by default and I thought it was probably time to upgrade them to python3.9 but was busy with other issues at the time. I'll do this presently.
