### ISSUE TITLE
Add "now-what" to local service starting

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#496]
### Use Case

The docs describe how to start a local service as a child, so it sits there listening to questions. I do `octue start` and get this (success):
![Screenshot 2022-07-16 at 12 11 18](https://user-images.githubusercontent.com/7223170/179352514-6c0003ac-30e8-4951-ac3f-585daa284aac.png)

My main question is "now what"? Is there a uri (e.g. localhost:post) I need to put into my parent to ask questions to this service? is there an emulated pubsub somewhere? Or are we using real pubsub and if so what's the topic name? I look in octue.yaml and I see the settings that are used in production but surely the local instance doesn't use the production pubsub queues.

This may be documented, in which case we could print a link to the documentation. Or we could put a few bits of info there to guide the user through whats next.

Here's an example of a kind of related thing. When I start a frontend server (using the gatsby framework, but that doesn't matter, just an example) I get a printout that tells me what to do next:
```
(my terminal) ~/source/octue/planex-site: gatsby develop

success open and validate gatsby-configs, load plugins - 2.521s
success Caching HTML renderer compilation - 0.459s

You can now view planex-site in the browser.

  http://localhost:8001/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8001/___graphql

Note that the development build is not optimized.
To create a production build, use gatsby build
```

**Comment by cortadocodes** [comment]
This will be a useful addition! Quick comment for you @thclark:

> surely the local instance doesn't use the production pubsub queues.

The local instance does use production Pub/Sub - the app is just *running* locally, not using a local Pub/Sub emulation. It's available as it would be if it were deployed (or the duration you keep it running. However, reading this issue and doing other recent work has made me realise we could add an `--offline` (or similar) option to the `octue start` CLI command which could use emulated Pub/Sub.
