### ISSUE TITLE
Instantiating with cloud metadata raises misleading warning

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#503]
### What happens

If I instantiate an octue dataset from a cloud path, it's natural to expect that the metadata on the newly instantiated datafiles will be consistent with what's in the cloud.

If I do:

```py
mast_timeseries = Dataset(path="gs://lake-mast-timeseries", recursive=True)
```

Then I get this:
```
WARNING:octue.resources.datafile:Overriding metadata given at instantiation with stored metadata for <Datafile('0b216b8c-2b2f-413b-96db-8448bc09ba18.txt')> - set `hypothetical` to `True` at instantiation to avoid this.
...hundreds more...
WARNING:octue.resources.datafile:Overriding metadata given at instantiation with stored metadata for <Datafile('298336e5-13ba-457b-99b0-813d0970005e.txt')> - set `hypothetical` to `True` at instantiation to avoid this.
ic| file: <Datafile('298336e5-13ba-457b-99b0-813d0970005e.txt')>
ic| file.metadata(): {'octue__id': '298336e5-13ba-457b-99b0-813d0970005e',
                      'octue__labels': LabelSet(),
                      'octue__sdk_version': '0.29.4',
                      'octue__tags': {'calm_threshold': 0.0,
                                      'elevation': 0.0,
                                      'latitude': 55.04449,
                                      'longitude': -5.66364,
                                      'met_mast_id': 'North Channel-NEWA',
                                      'timezone': 'UTC'},
                      'octue__timestamp': None}
```

At the time of invocation, cloud metadata looks like this:
![Screenshot 2022-07-19 at 12 19 01](https://user-images.githubusercontent.com/7223170/179738044-8f24faef-450b-408f-8d55-78576eb94e77.png)

So mostly the cloud metadata has made it intact to the local machine.

### Note on `octue_sdk_version`

The cloud metadata has been partially overwritten: the `octue_sdk_version` (which records the version of the SDK that last updated the file) has changed... but I haven't updated the metadata on the cloud object, so there will always be a disparity.

This is really about defining what the 'metadata()' on the Datafile really is. and I think if we define it as "metadata associated with the current instance" then this is probably correct but we need to be mindful of the fact that it's not 1:1 identical because this foxed me for a while.

### Problem with warnings and hypothetical parameter

I get hundreds of warnings from issuing a command where it's doing exactly as you'd expect, encouraging me to do something else. If I follow the instructions, adding `hypothetical=True`, that doesn't sync cloud metadata and as such gives me the following metadata:
```

DEBUG:octue.resources.dataset:Ignored stored metadata for <Dataset(df8e422b-0993-433f-8d83-ff50e3c04973)>.
DEBUG:octue.resources.dataset:Ignored stored metadata for <Dataset(df8e422b-0993-433f-8d83-ff50e3c04973)>.
ic| file: <Datafile('298336e5-13ba-457b-99b0-813d0970005e.txt')>
ic| file.metadata(): {'octue__id': 'ffcc5179-3846-40b7-aa07-126e8f70ea08',
                      'octue__labels': LabelSet(),
                      'octue__sdk_version': '0.29.4',
                      'octue__tags': {},
                      'octue__timestamp': None}
```

This of course isn't what I want. it's essentially a blank new file.

In the warning text it says `...Overriding metadata given at instantiation with stored metadata...` but this occurs AT instantiation, when I've given no metadata. It'd be understandable if I were syncing cloud metadata onto a Datafile for which I'd already supplied metadata (but I'm not sure that's even possible).

The `hypothetical` parameter is important because it allows us to skip syncing cloud metadata, which takes a long time if we don't need it and raises an exception if the file isn't in the cloud yet (i.e. we're preparing a cloud file but it's not uploaded yet).

But, it was always intended as a flag to handle that edge case, not for routine use. So huge cascades of warnings pointing us toward using it (especially when that's actually not what's typically required!) is a big UX issue.

I think we should:
- [x] remove that warning
- [x] consider renaming `hypothetical` to `skip_cloud_sync` or `create_new_cloud_file` which might be a bit more descriptive about purpose.
- [x] consider even further whether we could actually determine the hypothetical parameter and exclude it from the api altogether... It seems like the use case is mutually exclusive with there being a file in the cloud... when would we ever want to create a hypothetical file where one already exists?

**Comment by cortadocodes** [comment]
I think it still needs to be in the API for the situation where cloud files already exist but you don't want to fetch their metadata one request at a time because e.g. you have it synced to a database and can bulk collect it much faster. However, this isn't the behaviour needed when working interactively with datafiles and datasets so we need to be able to switch that on and off. Is that correct?

One thing we could do is have an environment variable like `IGNORE_STORED_METADATA` that, when present, has the same behaviour as providing the parameter that's currently available in `Datafile` and `Dataset` - then we could take that parameter out of the API. What do you think?

**Comment by thclark** [comment]
### Names

First, the proposed names don't reflect that it's *cloud* metadata, so I think 
`skip_cloud_meta_sync=True` or `OCTUE_SKIP_CLOUD_META_SYNC=1` 

### Instantiation-level control

I don't think just an environment variable is the right way to go. Because then in cases (like with django-twined) where I need to handle the edge case only in certain places in the code, I have to do:
```py
os.environ["SKIP_METADATA_SYNC"] = True
Datafile(**whatever)
os.environ.delete("SKIP_METADATA_SYNC")
```
to clear up after myself. In particular, setting the environ for a global behaviour to manage one specific edge case seems very wrong and god only knows if/how that'll work with async stuff.

A friendlier api for that case would be to be able to specify it at the instantiation.
```py
Datafile(**stuff, skip_cloud_meta_sync=True)
```

### If a global setting is needed

And I'm not sold on it at all... perhaps covering the case of automatically creating a bunch of stuff quickly for testing or whatever? Anyway, if there's a use case for needing that, the environment variable should be prefixed with `OCTUE` so everyone knows what it's for, eg:

`OCTUE_SKIP_CLOUD_META_SYNC`

**Comment by cortadocodes** [comment]
### Names
It's not necessarily cloud metadata - it can be local filesystem metadata instead (there are three places to get metadata - in-memory instance, local filesystem, or cloud).

### Instantiation-level control
Yeah I thought so too. The current state of the code is to provide that instantiation parameter to avoid this situation. I suggested a global setting as a possible solution to this:
>  consider even further whether we could actually determine the hypothetical parameter and exclude it from the api altogether... It seems like the use case is mutually exclusive with there being a file in the cloud... when would we ever want to create a hypothetical file where one already exists?
