### ISSUE TITLE
Cannot run tests using Runner without Google Credentials

### ISSUE THREAD

**Issue by nvn-nil** [octue/octue-sdk-python#508]
### What is the current behavior?

*If the current behavior is a bug, please provide any stack traces the steps reproduce and, if possible, a minimal demo of the problem.*

I set up `power-loss` on my colleague's system for running validations locally. All the tests in test_app fails with `DefaultCredentialsError` (full trace below). I have never noticed this because I always had the credentials set up. He's not part of the dev team and doesn't have GCP credentials (which we don't want anyway because we're running the service locally with local files).

I'm using an older version of octue (0.16.0) so I don't know if this is fixed in later versions. I'm switching to the latest version soon, so I'll try it then.

### What is the expected behavior?

I would like to run octue inside tests without valid google application credentials (given I'm using local files and no calls to child services)

### Your environment

  - Library Version: `0.16.0, extras: dataflow`
  - Platform: All

### More information

Here's a minimal example of the test which fails (for a real test, any test in test_app in power-loss will do)
```py
def test_app_case_1(self):
        with open(self.input_value_file_1) as f:
            input_values = json.load(f)

       files_dataset = Dataset(
            name="files_dataset",
            files=[
                Datafile(
                    path=path_to_file,
                    tags={"sequence": 0},
                )
            ],
        )

        input_manifest = Manifest(
            datasets={
                "files_dataset": files_dataset
            }
        )

        runner = Runner(app_src=App, twine=self.TWINE_PATH, children=self.children)
        analysis = runner.run(input_manifest=input_manifest.serialise(), input_values=input_values)

```

`runner = Runner(app_src=App, twine=self.TWINE_PATH, children=self.children)` checks for credentials before executing code in `app.py`

If you run it without setting `GOOGLE_APPLICATION_CREDENTIALS` with valid credentials (to raise the error I ran `GOOGLE_APPLICATION_CREDENTIALS=   python -m unittest tests.test_app.TestApp.test_run_calculation`). I get the error

```
Traceback (most recent call last):
  File "/workspaces/source_folder/tests/test_app.py", line 154, in test_run_calculation
    analysis = runner.run(input_manifest=input_manifest.serialise(), input_values=input_values)
  File "/usr/local/lib/python3.9/site-packages/octue/runner.py", line 108, in run
    inputs["children"] = {
  File "/usr/local/lib/python3.9/site-packages/octue/runner.py", line 109, in <dictcomp>
    child["key"]: Child(name=child["key"], id=child["id"], backend=child["backend"])
  File "/usr/local/lib/python3.9/site-packages/octue/resources/child.py", line 27, in __init__
    self._service = BACKEND_TO_SERVICE_MAPPING[backend_type_name](name=f"{self.name}-parent", backend=backend)
  File "/usr/local/lib/python3.9/site-packages/octue/cloud/pub_sub/service.py", line 62, in __init__
    self._credentials = auth.default()[0]
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 459, in default
    credentials, project_id = checker()
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 221, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 107, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File  was not found.
```

I tried creating a dummy JSON and set `GOOGLE_APPLICATION_CREDENTIALS` but it didn't work. I ended up mocking bits of octue to get the tests to run without checking credentials.

```py
            with patch(
                "octue.runner.Twine.validate",
                return_value={"children": {}, "input_values": input_values, "input_manifest": input_manifest},
            ):
                analysis = runner.run(input_manifest=input_manifest.serialise(), input_values=input_values)
```

Patching `validate` cannot be the solution because I don't want to lose twine schema validations and any other validations run by octue.

### Possible solution

Maybe a new boolean kwarg `local` can be passed to `runner.run` to force it to run fully isolated from the cloud.

**Comment by nvn-nil** [comment]
@cortadocodes @thclark this needs to be triaged

**Comment by cortadocodes** [comment]
Thanks for raising this. I have a few thoughts:
- What's the use case for someone who isn't developing `power-loss` running its tests? Shouldn't the tests be for the developers of the app and then actual users should just be able to use the app using `octue run` or by importing the app into a local python script?
- I agree the requirement for the credentials should be less general than it is now - I'll look at improving this

**Comment by nvn-nil** [comment]
> * `power-loss` does have a child - the `wake-service` - but I'm guessing `apply_wakes` or `layout_has_influenced_turbines` is `False` - could you confirm this is correct?

Yes, power loss can be run with or without wake service. We're currently running validations on the non-waked cases. The credentials are validated before anything in the app get's executed.

> * What's the use case for someone who isn't developing `power-loss` running its tests? Shouldn't the tests be for the developers of the app and then actual users should just be able to use the app using `octue run` or by importing the app into a local python script?

There's no reason a user shouldn't be able to run tests that don't access cloud files. We are skipping tests (locally) that do depend on cloud resources (the test_deployment tests).

The use case is unrelated to tests. He's running validations locally because it's quicker to run. I think I'll run into the same bug even if run a question using `Runner.run` in a local script. I'm already doing it, it's just that the test suite runs it for me. I wanted to run the cases through the `Runner`, instead of importing the classes directly because I wanted him to test that all the inputs he's working with pass twine schema and other validations.

**Comment by cortadocodes** [comment]
That makes sense, thanks. I'll probably get time to solve this tomorrow

**Comment by cortadocodes** [comment]
It will require the latest (at the point I solve it) version of `octue` though. Where are we at with updating `power-loss` to use the latest version since the breaking changes to do with datasets?

**Comment by nvn-nil** [comment]
We're going to make the move soon. I have some chores to do on power loss and we'll update everything to the latest version of octue soon.
