### ISSUE TITLE
Topic class shouldn't require a service to instantiate

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#520]
### Use Case

I'm trying to use the `Topic` class to create a topic on GCP. I need to do this as part of a devops pipeline, because each time I deploy a new tagged version of a service (i.e. having a Service Revision Unique IDentifier) I need to create a topic specific to it, so I can ask questions of that particular revision. I also need to create a subscription to the corresponding topic.

### Current state

Conceptually, a `Topic` is completely separate to a `Service`. In terms of resources there's no coupling at all.  However, at present, a `Topic` must be instantiated with a `Service` instance. This seems to be purely so that the `Topic` class can access the service's `publisher` client when it should just have a client of its own.

### Recommended solution

Give `Topic` class its own publisher so we can create a `Topic` without also creating a `Service`.

### Sidebar

The [gcp-pilot project has some quite sensible patterns we could draw on](https://github.com/flamingo-run/gcp-pilot/blob/265d16671adc369e8e8b5257538bb4c4bcea41a4/gcp_pilot/pubsub.py#L20) and I'd like to recommend using it out of the box, but their maintenance is super weird, they don't seem to engage with issues and they're deprecating support for python versions very quickly, which means it [can't be used with a lot of google's own tooling](https://cloud.google.com/dataflow/docs/concepts/sdk-worker-dependencies) (that says more about google than gcp-pilot but still not a wise choice for a lib trying to interface with google!!!)

**Comment by cortadocodes** [comment]
Great point - will update.
