### ISSUE TITLE
`delivery_acknowledgement` missing from message list

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#532]
### What is the current behavior?

Docs [here](https://github.com/octue/octue-sdk-python/blob/main/docs/source/testing_services.rst#message-types) include a list of message types that can be received by a parent.

`delivery_acknowledgement` is missing.

### What is the expected behavior?

`delivery_acknowledgement` should be present in the list.

**Comment by cortadocodes** [comment]
I left this out because the emulator automatically sends this message to the parent. The emulator always receives the messages sent to it by the parent so I'm not sure if it makes sense to allow the user of the emulator to provide `delivery_acknowledgement` messages?
