### ISSUE TITLE
Crash diagnostics doesn't save original input_values

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#538]
### What is the current behavior?

When crash diagnostics are saved, the `input_values` object is saved with them (of course). But, the object that gets saved is a re-serialised version of the original input values; ie it is *mutable*.

For example, doing `input_values.pop('whatever-property', None)` in an app which subsequently crashes will save the crash diagnostics with an absent value for `whatever-property`. When used to recreate the crash, this may 

### What is the expected behavior?

The `input_values` saved in crash diagnostics should be the serialised input values that reach the service; i.e. they should not be roundtripped through deserialization and serialization, so they're always original. This captures any problem with their initial deserialization, as well as solving the mutability problem.

**Comment by cortadocodes** [comment]
I think this applies to all of:
- Input values
- Input manifest
- Configuration values
- Configuration manifest
