### ISSUE TITLE
Easy construction of test case fixture from crash diagnostic

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#539]
### Background 

If a service fails with an error of some kind:
```
ERROR runner.py:209 [windpioneers/wake-service:0-7-11 | analysis-dc643314-aec2-4326-9e8b-a00900c60366] No points given
```

The natural next step is to get crash diagnostics....
`octue get-crash-diagnostics wake-service-crash-diagnostics/dc643314-aec2-4326-9e8b-a00900c60366`

This downloads a folder structure which:
- points to remote files in the manifest, but
- has local files downloaded (but they're in a directory structure comprising locally saved temporary files.

![Screenshot 2022-10-24 at 15 45 34](https://user-images.githubusercontent.com/7223170/197555084-181a5e56-f049-4337-a3e3-6d3920c7f96e.png)
![Screenshot 2022-10-24 at 15 45 16](https://user-images.githubusercontent.com/7223170/197555094-d50e3171-fa81-4d4c-a101-d1f47f48fd8a.png)

This is the worst of both worlds, because:
- we can trigger a question using these input values, but files are downloaded from remote every time
- we can't use local files to run a test fixture without downloading an entire manifest.

What we next do, is create a `make_fixture.py` file in the downloaded folder, which instantiates a test fixture usable in pytest.

The `make_fixture.py` file looks something like this:
```py
import json
import os
from octue.resources import Dataset, Manifest


def make_fixture(serialise=True):
    """Create inputs for testing the service using using local fixture files.

    :parameter bool serialise: Serialise the inputs for use with the octue test runner (default true)
    :return (dict|string, dict|string, dict): The input_values, input_manifest and expected_output_values of the run
    """

    # Load input values from the fixture
    path = os.path.dirname(__file__)

    with open(os.path.join(path, "sandy-sands-wake-service-input-values.json"), encoding="utf-8") as fp:
        input_values = json.load(fp)

    input_values["wake_parameters"] = {"apply_wake": True}

    # Create input manifest using local fixture data (rather than remote)
    input_manifest = Manifest(
        datasets={
            "wind_speed_map": Dataset(os.path.join(path, "wind_speed_map")),
            "elevation_map": Dataset(os.path.join(path, "elevation_map")),
        }
    )

    # Serialise the inputs for use with the app test runner
    if serialise:
        input_values = json.dumps(input_values)
        input_manifest = input_manifest.serialise()

    return input_values, input_manifest, None

```

And that's then used in test folders something like:
```py

import logging
import unittest
import pandas as pd
from octue import Runner
from tests._base import BaseTestCase
from tests.data.sandy_sands import sandy_sands_fixture


logger = logging.getLogger()
logger.setLevel(logging.INFO)


class TestApp(BaseTestCase):
    def test_sandy_sands(self):
        """Sandy sands demo site test case. This raised 'no points given' exception because
        nrows and ncols were incorrectly used in latlon_grid method of AsciiWindMapReader
        """

        # Get the inputs for this fixture
        input_values, input_manifest, _ = sandy_sands_fixture.make_fixture()

        # Create an app runner and run the full app.
        runner = Runner(
            app_src=self.app_src_path,
            twine=self.twine_path,
        )

        analysis = runner.run(input_manifest=input_manifest, input_values=input_values)
        self.assertTrue("wake_efficiencies" in analysis.output_values)

```

### Use case

- [x] When downloading crash diagnostics, we want to be able to:
  - [x] Download JUST the `input_manifest`, `input_values` and `messages` files, with gs://path addresses to file locations.
  - [x] Download datasets too, converting the `input_manifest` to use corresponding local paths
- [x] We want the local paths, when downloaded, to be meaningful and not temporary files.
- [x] We also want to be able to seamlessly create a test fixture immediately from the downloaded data, like with `octue.get_fixture('sandy/sands/fixture/directory)` or a class based method.

**Comment by thclark** [comment]
@cortadocodes if a service has any children, and you're gathering crash diagnostics for the service, can you set up the child emulator too, in terms of any i/o with the child? 

We also need to be able to assert in our test that the inputs sent to the child emulator during the test match the ones that were sent to the child in this fixture.

**Comment by cortadocodes** [comment]
> We also need to be able to assert in our test that the inputs sent to the child emulator during the test match the ones that were sent to the child in this fixture.

I'm going to add this as a separate feature: https://github.com/octue/octue-sdk-python/issues/543
