### ISSUE TITLE
Clean up dataset file artifacts left behind by a run

### ISSUE THREAD

**Issue by nvn-nil** [octue/octue-sdk-python#547]
### Use Case

Files that are downloaded by a service will remain in /tmp and will build up over multiple runs.

We've been getting OOM errors from cloud run (I've always thought those were ephemeral) using second-generation execution environment when many runs are triggered really quickly. Each run downloads about 300-400MB of datalake files and we're using large memory (8GB) instances.

We have multiple services and in one of them (power-loss), I delete all the dataset files after a run because we had the same problem. I was going to do it in wake service right now but thought I'd see what you guys think about this before I do it.

Feel free to close this issue if this is not something that will be implemented here.

### Current state

Files in a dataset fills up space in disk (/tmp) over time. In cloud run with in-memory file store this uses up memory which it shouldn't because it's supposed to not be persistent but idk.

![image](https://user-images.githubusercontent.com/58132281/202389934-dd5b6441-89ee-4c98-8897-5294d34cc284.png)

**Comment by cortadocodes** [comment]
Have you implemented anything in the meantime?

**Comment by nvn-nil** [comment]
I keep track of the files I download and delete them before finalizing
