### ISSUE TITLE
Runner().run() method within parent twin: Avoid using 'app' as a python module, except for your main entrypoint

### ISSUE THREAD

**Issue by time-trader** [octue/octue-sdk-python#57]
**I'm submitting a ...**
  - [x] support request
  - [ ] bug report
  - [ ] feature request
  
Please fill out the relevant sections below.

---

## Support request

I'm trying to use a Runner(). run() method to run a "child twin" from another "parent" twin.  What would be a proper setup for this?

### Use Case

Parent twins.

### Current state

Running [FSI Simulation](https://gitlab.com/windenergie-hsr/aerosense/digital-twin/fsi-twins/fsi-simulation) twin: 
 `octue-app run --data-dir "data" ` 
Returns:
`"Module 'app' already on system path. Using 'AppFrom' context will yield unexpected results. Avoid using 'app' as a python module, except for your main entrypoint"`

### Your environment
  
  - Library Version: Octue 0.1.6
  - Platform Linux

**Comment by thclark** [comment]
Thanks @time-trader we'll cover this as we move on to #46 which will be our work for tomorrow and the day after!

**Comment by thclark** [comment]
Being able to handle multiple children locally might give us an elegant way of solving https://github.com/octue/twined-server/issues/2 at the same time, enabling one server to run a network of services.

**Comment by cortadocodes** [comment]
This is (partially?) solved by running children as serving `Service`s (see #79 which should make up part of the next release) in different python processes e.g.
* In different terminals running python with or without a virtual environment activated in each one
* By using something like `subprocess.Popen` to run different python processes from a python process

I'll be looking more into this soon to find fuller solutions.

**Comment by cortadocodes** [comment]
The remote version of this has been addressed by creating automatic Google Cloud Run deployments in #124
