### ISSUE TITLE
Include more debug information in the crash diagnostics

### ISSUE THREAD

**Issue by nvn-nil** [octue/octue-sdk-python#573]
### Use Case

Recently, we've had issues with services missing delivery ack (fixed as of [0.43.3](https://github.com/octue/octue-sdk-python/tree/0.43.3)) and to debug it we needed to get the messages and the debug logs from the failed run. 

I could dig into the octue internals to get the messages but it would be ideal if octue includes these in the crash diagnostics. And for the debug level logs, it'd be useful to add a new internal handler (maybe a file handler) with debug level filters to get the logs which can also then be included in the crash diagnostics.

Our services are running with info-level logs and we'd like to keep it that way because some non-software engineers keep an eye on these logs to see what's happening with the service. So, when there's an error we'd have to deploy a new debug revision, recreate the issue (problem because not all bugs can be recreated on demand), get the logs, then release a non-debug revision of the service.

**Comment by nvn-nil** [comment]
@cortadocodes Could you triage this?

**Comment by thclark** [comment]
This would be nice but unfortunately isn't practical for performance reasons.

When issuing a log, eg with `logger.debug('Something happened with %s', value)`, python's logging framework accepts the invocation of `logger.debug`, then checks the log level **before** doing the following work:
- rendering the string message with its arguments
- introspecting the call stack (if necessary eg for exceptions)
- placing the log onto the buffer
- (buffer) sending that to the handler(s)

**Comment by thclark** [comment]
Except in the event of a catastrophic error like a SegFault (in which case you wouldn't get crash diagnostics saved anyway), the message queue is flushed during exception handling so there shouldn't be any missing messages that don't get forwarded to the communications backend.
