### ISSUE TITLE
Consider removing `deploy` commands from CLI

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#575]
Terraform and GitHub actions have provided a more reliable, transparent, and robust way to deploy our services to the cloud. We should consider remove the `octue deploy cloud-run` and `octue deploy dataflow` commands from the CLI if we no longer need them.

**Comment by thclark** [comment]
Agreed. Even though it took a long time to build them, they've always been out of place. I'd rather provide a terraform library and some out-of-the-box github actions.

**Comment by cortadocodes** [comment]
Yep I think it was a useful exercise and also highlighted that Terraform and GHAs are the way forwards
