### ISSUE TITLE
Dataset has no len()

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#59]
**I'm submitting a ...**
  - [ ] support request
  - [ ] bug report
  - [x] feature request
  
Please fill out the relevant sections below.

---

### Use Case

I'm creating a dataset to match NASA's Digital Elevation Model, and want to cross-check that I've added all 22911 files to it.

### Current state
```
print(dataset)
>>> Dataset 7430991f-bf5e-4e17-8a42-b44e02495717

len(dataset)
>>> Traceback (most recent call last):
>>>   File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in >>> Exec
>>>     exec(exp, global_vars, local_vars)
>>>   File "<input>", line 1, in <module>
>>> TypeError: object of type 'Dataset' has no len()
```

### What is the expected behavior?

To return the number of files in the dataset

### Workaround:
```
print(len(dataset.files))
>>> 22911
```

**Comment by cortadocodes** [comment]
This is a sub-feature in #50! I'll reference it there
