### ISSUE TITLE
Make Question chains easily extractible from BigQuery Event Store

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#649]
### Use Case

We want to be able to extract the sequence of all events that were triggered throughout the process of a grandparent question being executed.

### Current db

![Screenshot 2024-04-24 at 11 18 46](https://github.com/octue/octue-sdk-python/assets/7223170/03ee0cf0-59de-4668-8cb0-48fe4405fb37)

### Proposed Solution

This means we have to maintain a linked list so that a grandchild's events can be associated with a grandparent's questions.

### Defining terms
- Originator:  refers to the ultimate service or question which triggered the entire tree of questions (and the corresponding sequence of events from each). Synonymous with "ultimate ancestor/parent".

### Implementation

- [x] If each event has a `parent_question_uuid` and a `question_uuid` then we have a linked list that we can traverse
- [x] We probably should also require an `originator_question_uuid` (for subscription purposes and for eliminating the need to recurse queries to resolve the linked list in some query scenarios).
- [x] Rename the current `originator` column to `parent`
- [x] Make a new column called `originator` to record the originator service
- [x] Update `get_events` function
- [x] Consider updating to ordering by datetime for events (keep the order column for now, we may require it later). This is to allow proper ordering of all events in a question chain. 
- [x] Update cloud function
- [x] Redeploy cloud function where needed
- [x] Update and redeploy bigquery table where needed
- [x] Test with example service
- [ ] Write test of question chaining
- [x] Update documentation
- [x] Test with existing service

**Comment by cortadocodes** [comment]
@thclark do you think we should have an `originator_question_uuid` too? This will make it easier to retrieve all events triggered by an original question at any level.
