### ISSUE TITLE
Optimise log messages

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#77]
Some of the log messages are interpolating variables even when they're not being emitted. We can avoid this, saving lots of processing, by not interpolating but by using percent-notation and passing the variables in to e.g. `logger.info` as extra positional arguments. i.e.
```
a = 3
logger.info('This is %s', a) 
```
rather than
```
a = 3
logger.info(f'This is {a}') 
```

This applies to all repos using python logging.

**Comment by thclark** [comment]
Yeah I would normally do that but for a while was print() ing things (before the loggers got hooked up properly they weren't propagating into the test client, and I guess I just did quick conversion from print to log.

Fix them as you see them, and we should make it a point to request changes on a review if we see this practice.

**Comment by cortadocodes** [comment]
I think some of them are mine too! Will do
