### ISSUE TITLE
Update CLI

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#9]
Redesign CLI to a single CLI, instead of a mechanism that defines a new CLI for every app.

- [x] give an app path argument to specify which app to run
- [x] allow user to specify a --data-dir argument which, on instantiation of Analysis(), gives a hint to the location of sources which aren't specified on the command (allowing use straight from the terminal)
- [x] get version from git or from setup.py to remove the need for `@octue_version` decorator
- [x] remove deprecated `logs` directory
- [ ] add CLI usage instructions to README

**Comment by cortadocodes** [comment]
Requirements:
1) We need to be able to find input and configuration datasets (i.e. a data path)
2) We need to know where to write output datasets (i.e. a data path)
3) We need to be able to read the manifest data (for configuration and inputs) from a src, which can be a file or raw json
4) We need to be able to write the output manifest to a file (and need to know where that is)
5) We need to be able to write the output_values to a file (and know where that is)

**Comment by cortadocodes** [comment]
Based on conversation on 2020-10-31, I've removed this part of the issue: `give input sources arguments (e.g. src can be a data path or a json string`
